; docker/php/php.ini

expose_php = Off ; Don't advertise PHP version in headers
display_errors = Off ; Never show errors to the browser in prod
log_errors = On ; Enable error logging
error_log = /var/log/php_errors.log ; PHP Error log location

upload_max_filesize = 10M ; Maximum size allowed for body content
post_max_size = 12M ; Maximum total size allowed for POST requests
max_execution_time = 15 ; Max time (seconds) a script can run 
memory_limit = 128M ; Max memory a single script can consume

session.cookie_httponly = 1 ; Prevents Javascript from accessing cookie data
session.cookie_secure = 1 ; Send cookies only over HTTPS
session.use_strict_mode = 1 ; Reject uninitialized session IDs
